version: "3.4"
services:

  init-geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: lukso-geth-init
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    command: >
      --datadir=/execution_data init /configs/shared/genesis.json

  geth:
    image: ethereum/client-go:$GETH_VERSION
    container_name: lukso-geth
    depends_on:
      - init-geth
    volumes:
      - $EXECUTION_DATA_VOLUME:/execution_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --datadir=/execution_data
      --ws
      --ws.api "eth,net,web3,engine"
      --ws.addr 0.0.0.0
      --ws.origins "*"
      --networkid $GETH_NETWORK_ID
      --http
      --http.api "eth,net,web3,engine"
      --http.addr "0.0.0.0"
      --http.corsdomain "*"
      --http.vhosts "*"
      --verbosity $GETH_VERBOSITY
      --ipcdisable
      --port $GETH_PEER_PORT
      --http.port $GETH_HTTP_PORT
      --metrics
      --metrics.addr "0.0.0.0"
      --authrpc.jwtsecret /configs/jwt.hex
      --miner.gaslimit 42000000
      --miner.gasprice 1000000000
      --nat extip:$EXTERNAL_IP
      --bootnodes $GETH_BOOTSTRAP_NODE
     # --ethstats "${NODE_NAME}:${ETH_STATS_SECRET}@${ETH_STATS_ADDRESS}"
    network_mode: host

  prysm_beacon:
    image: prysmaticlabs/prysm-beacon-chain:$PRYSM_BEACON_VERSION
    container_name: prysm_beacon
    depends_on:
      - geth
      - eth2stats-client
    volumes:
      - $CONSENSUS_DATA_VOLUME:/consensus_data
      - $CONFIGS_VOLUME:/configs
    restart: unless-stopped
    stop_signal: SIGINT
    stop_grace_period: 2m
    command: >
      --accept-terms-of-use
      --genesis-state=/configs/shared/genesis.ssz
      --datadir=/consensus_data
      --execution-endpoint=http://localhost:8551
      --jwt-secret=/configs/jwt.hex
      --min-sync-peers=0
      --p2p-host-ip=$EXTERNAL_IP
      --chain-config-file=/configs/shared/config.yaml
      --monitoring-host 0.0.0.0
      --grpc-gateway-host 0.0.0.0
      --rpc-host 0.0.0.0
      --verbosity $PRYSM_VERBOSITY
      --suggested-fee-recipient $FEE_RECIPIENT
      --p2p-max-peers 250
      --subscribe-all-subnets
      --minimum-peers-per-subnet 0
      --block-batch-limit 512
      --block-batch-limit-burst-factor 10
      --bootstrap-node $PRYSM_BOOTSTRAP_NODE
     # --contract-deployment-block {{ contract_deployment_block }}
    network_mode: host
  
  # # prysm_validator_import:
  # #   image: prysmaticlabs/prysm-validator:v4.0.1
  # #   container_name: prysm_validator_import
  # #   volumes:
  # #     - $KEYSTORE_VOLUME:/keystore
  # #     - $VALIDATOR_DATA_VOLUME:/validator_data
  # #     - $CONFIGS_VOLUME:/configs
  # #     - $TMP_VOLUME:/tmp/secrets
  # #   command: >
  # #     accounts import
  # #     --accept-terms-of-use
  # #     --keys-dir=/tmp/secrets
  # #     --wallet-dir=/keystore/prysm
  # #     --wallet-password-file=/tmp/secrets/password.txt
  # #     --account-password-file=/tmp/secrets/password.txt
  
  eth2stats-client:
    image: macht/eth2stats-client:v1.0.0
    container_name: eth2stats-client
    restart: unless-stopped
    command: >
      run
      --beacon.type=prysm
      --eth2stats.node-name=$NODE_NAME
      --eth2stats.tls=false
      --beacon.metrics-addr=http://127.0.0.1:8080/metrics
      --beacon.addr=127.0.0.1:4000
      --eth2stats.addr=$ETH_2_STATS_ADDRESS
    network_mode: host